### PR TITLE
New Grammar 5.0 SSVE

### PR DESCRIPTION
**Pull request by Abhijay**
Contains changes for:
-New 5.0 spec
-Search bar fix (app.js replaced by search.js and inclusion of new grammar 5.0 data.json file)
-Choice value node
-"Value: " prefix to value nodes

Doesn't contain changes for:
-Value node ambiguity in showing when explicit and not showing when inherited.

(I have yet to replace the CNAME file, so it's still up at Abhijay.github.io to view. Once approved, I'll add it back.)

### CODE REVIEW

**Comment by Abhijay** [comment]
In terms of managing git history, let me know if you'd like me to rebase and squash the commits.

**Comment by Dtphelan1** [comment]
Looks good all-in-all. Two things I would recommend: 
1. It looks like the /_includes/spec folder still exists from when we were using a template driven approach to build the SHR spec pages. Let's remove that since the output of SSVE is no longer template pages but instead full HTML pages. 
2. We still have FHIR and FHIR5G as two separate folders. Now since the rest of the website is catching up with grammar five, let's get rid of G5 and just use the FHIR folder, containing the G5 files. 

I'll review again when those changes have been made, but like I said the core functionality looks good still.

**Comment by Abhijay** [comment]
Pushed those changes. Let me know if there's anything else.

**Review by Dtphelan1 — APPROVED** [review]
Not that I can think of. It seems to pass all of the tests we've come up with, and as for my typical walkthrough of tests: 
1. Check that the viz works, particularly for newly added elements.
2. Check that search works, particularly for newly added elements.
3. Check  that the FHIR files exist, particularly for newly added elements.
4. Check  that cannonical FHIR paths, particularly for newly added elements. 
5. Check that namespace pages work, particularly for newly added elements.
6. Check that valueset pages work, particularly for newly added elements.
7. Check that codesystem pages work, particularly for newly added elements.

Everything looks clear on my end.

**Pull request merged**
